### ISSUE TITLE
Problems I encountered when I tried to reproduce the model

### ISSUE THREAD

**Issue by syqisme** [williamium3000/diverse-cotraining#1]
Hello, in the process of trying to reproduce the model in the paper, I found that the miou result obtained by using the branch of segformer was always higher than the branch of resnet101, about 2 percentage points higher. Would you like to ask whether the result in the paper shows the branch of resnet? And how do I solve the problem of unifying the results of the two branches?

**Comment by williamium3000** [comment]
Hi, we report the highest of all co-trained models. We observe that in some settings, ResNet is higher than transformer. There are no effective solutions to unifying the results of the two branches, one of the possible ways is to use better CNN branches with higher performance. For instance, one can use ResNeSt backbone or convnext. One can also use better segmentation head to close up the gap.

**Comment by syqisme** [comment]
Your reply has solved my confusion. Thank you very much！
