### ISSUE TITLE
OSError: libjpeg-turbo-2.0.3/build/libturbojpeg.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wenbobaba** [williamium3000/diverse-cotraining#2]
问题：
    当我运行shell脚本时报错：“OSError: libjpeg-turbo-2.0.3/build/libturbojpeg.so: cannot open shared object file: No such file or directory”。我怀疑这与我没有安装libjpeg-turbo有关。
为了解决问题的尝试：
    我运行安装命令apt install libjpeg-turbo时候发生报错，无法定位软件包，于是为了安装jpeg2dct，我使用了sudo apt-get install libjpeg-dev来安装libjpeg-dev，然后安装了jpeg2dct。
    我还按照网上的教程手动下载了libjpeg-turbo-2.0.3，运行sudo make install用后来下载的libjpeg-turbo-2.0.3替换了您的文件中的libjpeg-turbo-2.0.3，但是仍然有这个问题。

**Comment by williamium3000** [comment]
Theoretically, installing libjpeg-dev by 
`sudo apt-get install libjpeg-dev`
is sufficient to run the code. I have tested this on multiple systems.
I believe the problem is that after you install libjpeg-dev, there are some files that are not linked to correct places.
